apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stalwart-webmail
  namespace: example-org
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: webmail.example-org.TEMPLATE_DOMAIN
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - webmail.example-org.TEMPLATE_DOMAIN
      secretName: stalwart-tls
  rules:
    - host: webmail.example-org.TEMPLATE_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stalwart
                port:
                  number: 8080
