apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.secret.template.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
  - dnsendpoint.yaml
