apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - namespace.yaml
  - helm-repository.yaml
  - prometheus.yaml
  - ingress.yaml
  - network-policy.yaml
