apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - helm-repository.yaml
  - secrets.secret.template.yaml
  - grafana.yaml
  - ingress.yaml
  - network-policy.yaml
