# Tenant Flux Kustomizations
---
# Example Organization tenant
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-example-org
  namespace: flux-system
spec:
  interval: 10m
  path: "./manifests/tenants/example-org"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: postgresql-operator
    - name: redis-operator
    - name: cert-manager-post-setup
    - name: nginx-ingress
    - name: external-dns
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kanidm
      namespace: example-org
    - apiVersion: apps/v1
      kind: StatefulSet
      name: stalwart
      namespace: example-org
