apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - postgres.yaml
  - helm-release.yaml
  - secrets.secret.template.yaml
  - ingress.yaml
  - certificates.yaml
  - service-monitor.yaml
  - network-policy.yaml
