# Mattermost secrets
# Encrypt with: sops --encrypt --in-place secrets.secret.template.yaml
# Then rename to secrets.secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres-credentials
  namespace: mattermost
type: Opaque
stringData:
  username: "mattermost"
  password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-secrets
  namespace: mattermost
type: Opaque
stringData:
  at-rest-encrypt-key: "CHANGE_ME"
  public-link-salt: "CHANGE_ME"
  smtp-username: "CHANGE_ME"
  smtp-password: "CHANGE_ME"
  gitlab-secret: "CHANGE_ME"
