apiVersion: v1
kind: Service
metadata:
  name: kanidm
  namespace: example-org
spec:
  selector:
    app: kanidm
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: ldap
      port: 3636
      targetPort: 3636
      protocol: TCP
  type: ClusterIP
