apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- litellm-deployment.yaml
- litellm-config.yaml
- expense-tracker.yaml
- secrets.secret.template.yaml
- ingress.yaml
- service-monitor.yaml
- network-policy.yaml
