apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
  - namespace.yaml
  - secrets.secret.template.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingress.yaml
