# Redis password for tenant
# Encrypt with: sops --encrypt --in-place secrets.secret.template.yaml
# Then rename to secrets.secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-org-redis-secret
  namespace: example-org
type: Opaque
stringData:
  password: "CHANGE_ME"
